# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :tests do
    # ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    # ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "5"
    scan(
      project: "CIDemo.xcodeproj",
      scheme: "CIDemo",
      testplan: "CITest",
      code_coverage: true,
      result_bundle: true,
      output_directory: "fastlane/test_output",
      destination: "platform=iOS Simulator,name=iPhone 17 Pro,OS=26.5"
    )
  end

  lane :danger do
    danger(dangerfile: "Dangerfile.yml")
  end

end
