on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-26-xlarge

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Select Xcode 26.4
        run: |
          sudo xcode-select -s /Applications/Xcode_26.4.app/Contents/Developer
      
      - name: Verify Xcode Version
        run: |
          xcode-select -p
          xcodebuild -version
      
      - name: List Simulators
        run: xcrun simctl list devices available
      
      - name: Boot Simulator
        run: |
          xcrun simctl boot 86C81BD8-3941-4DB2-A7E0-41895F011C48
          xcrun simctl bootstatus 86C81BD8-3941-4DB2-A7E0-41895F011C48 -b

      - name: Build App
        run: |
         xcodebuild \
         -project CIDemo.xcodeproj \
         -scheme CIDemo \
         -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.4'
         clean build \
         CODE_SIGNING_ALLOWED=NO